
default: &default
  adapter: <%= ENV.fetch("ADAPTER") %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DB_PORT")%>
  host: <%= ENV.fetch("HOST") %>
  timeout: 5000
  
development:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

test:
  <<: *default
  database: test_db
  username: postgres
  password: postgres

staging:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

